### ISSUE TITLE
obs-multisource-effect include audio or not?

### ISSUE THREAD

**Issue by kirahan** [norihiro/obs-multisource-effect#12]
I'm try to use obs websocket to design a remote controller of obs.
when I handle audio configs I was confuse by this plugin.
The GetSourceTypesList method get from obs websocket show this type source don't include audio ability.
But when I mix an video include audio with another source, it will show audio bar.
![微信截图_20220120200930](https://user-images.githubusercontent.com/7088329/150336260-8d7782dd-347d-4877-b5b4-547a01036264.png)

**Comment by kirahan** [comment]
![微信截图_20220120201116](https://user-images.githubusercontent.com/7088329/150336440-f55a8a82-9e73-4c01-bb17-a02a2a21cafc.png)

**Comment by norihiro** [comment]
>  obs-multisource-effect include audio or not?

No, this source does not have audio.

When this source goes to the program, it the active state propagates to the sources of this plugin. I think that's why these sources are displayed on your audio mixer. It won't affect your streaming or recording audio.

**Workaround**: If you want to have audio, I recommend to have the source with small size and located underneath the multisource-effect so that the audio of the source goes to the streaming or recording.

**Comment by kirahan** [comment]
ok
